[workspace]

[package]
name = "logenough"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "3.4.2"
circular-buffer = "0.1.6"
parking_lot = "0.12.1"
eframe = "0.28.1"
egui_extras = { version = "*", features = ["all_loaders"] }
image = { version = "0.25", features = ["png"] }